<?php

declare(strict_types=1);

// The repository can contain package discovery files generated by a local
// development install. Vercel omits require-dev packages, so those manifests
// must be rebuilt from the production dependency set.
foreach (['packages.php', 'services.php'] as $manifest) {
    $manifestPath = dirname(__DIR__).'/bootstrap/cache/'.$manifest;

    if (is_file($manifestPath)) {
        unlink($manifestPath);
    }
}

// mPDF ships fonts for dozens of writing systems. Mihwar reports use XB Riyaz
// and DejaVu for Arabic/Latin content, so keep those families in Vercel builds.
$fontDirectory = dirname(__DIR__).'/vendor/mpdf/mpdf/ttfonts';

if (! is_dir($fontDirectory)) {
    exit(0);
}

$keptPrefixes = ['DejaVu', 'XB Riyaz'];

foreach (glob($fontDirectory.'/*') ?: [] as $fontPath) {
    if (! is_file($fontPath)) {
        continue;
    }

    $fontName = basename($fontPath);
    $keep = false;

    foreach ($keptPrefixes as $prefix) {
        if (str_starts_with($fontName, $prefix)) {
            $keep = true;
            break;
        }
    }

    if (! $keep) {
        unlink($fontPath);
    }
}
