@extends('layouts.panel')
@section('title','العروض والتحصيل')
@section('content')
@php
    $openInstallments=$installments->whereIn('status',['pending','partial']);
    $overdue=$openInstallments->filter(fn($i)=>$i->due_on->isPast());
@endphp
<h1>العروض والتحصيل</h1><div class="sub">من عرض السعر إلى العقد وجدول الدفعات وسند القبض، مع إبقاء كل إصدار وسجل مالي دون تعديل رجعي.</div>
<div class="kpis"><div class="kpi"><div class="v">{{ $quotations->where('status','sent')->count() }}</div><div class="l">بانتظار اعتماد العميل</div></div><div class="kpi"><div class="v">{{ number_format($openInstallments->sum(fn($i)=>$i->remaining()),2) }}</div><div class="l">المبالغ المفتوحة</div></div><div class="kpi"><div class="v" style="color:{{ $overdue->isNotEmpty()?'var(--red)':'inherit' }}">{{ $overdue->count() }}</div><div class="l">دفعات متأخرة</div></div><div class="kpi"><div class="v">{{ $contractsEnding->count() }}</div><div class="l">عقود تنتهي خلال 60 يومًا</div></div></div>

<div class="card"><div class="hd">عرض سعر جديد</div><div class="bd"><form method="POST" action="{{ route('panel.quotation.store') }}">@csrf
<div class="grid3"><div class="field"><label>العميل</label><select name="client_id" required>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div><div class="field"><label>عنوان العرض</label><input name="title" value="عقد صيانة سنوي" required></div><div class="field"><label>الباقة</label><select name="package_code"><option value="basic">أساسي</option><option value="comprehensive">شامل</option></select></div></div>
<div class="grid3"><div class="field"><label>سعر الدورة قبل الضريبة</label><input name="price_amount" type="number" step="0.01" required></div><div class="field"><label>دورة الدفع</label><select name="billing_cycle"><option value="monthly">شهري</option><option value="quarterly">ربع سنوي</option><option value="upfront">دفعة واحدة مقدمة</option><option value="custom">دفعات مخصصة</option></select></div><div class="field"><label>المدة بالأشهر</label><input name="duration_months" type="number" value="12" min="1" max="60" required></div></div>
<div class="grid2"><div class="field"><label>مقدم إضافي قبل الضريبة</label><input name="down_payment_amount" type="number" step="0.01" value="0" min="0"></div><div class="field"><label>دفعات مخصصة: التاريخ|المبلغ، سطر لكل دفعة</label><textarea name="custom_installments_text" rows="3" placeholder="2026-09-01|5000&#10;2026-12-01|3000"></textarea></div></div>
<div class="grid3"><div class="field"><label>بداية العقد المقترحة</label><input name="starts_on" type="date" value="{{ now()->addWeek()->toDateString() }}" required></div><div class="field"><label>صلاحية العرض حتى</label><input name="valid_until" type="date" value="{{ now()->addDays(14)->toDateString() }}" required></div><div class="field"><label>الضريبة</label><input name="vat_rate" type="number" step="0.01" value="0.15" required></div></div>
<div class="grid3"><div class="field"><label>نافذة الخدمة من</label><input name="service_window_start" value="07:00" required></div><div class="field"><label>إلى</label><input name="service_window_end" value="23:00" required></div><div class="field"><label>SLA بالدقائق</label><input name="sla_minutes" type="number" value="240" required></div></div>
<div class="field"><label>المواقع المشمولة</label>@foreach($clients as $client) @foreach($client->sites as $site)<label style="display:inline-flex;align-items:center;gap:5px;margin-inline-end:12px"><input type="checkbox" name="site_ids[]" value="{{ $site->id }}" style="width:auto">{{ $client->name }} — {{ $site->name }}</label>@endforeach @endforeach</div>
<div class="field"><label>الشروط — شرط في كل سطر</label><textarea name="terms_text" rows="3">الأسعار قبل ضريبة القيمة المضافة&#10;الأعمال الإضافية تحتاج موافقة مستقلة&#10;العرض صالح حتى التاريخ الموضح</textarea></div><button class="btn">حفظ المسودة</button></form></div></div>

<div class="card"><div class="hd">عروض الأسعار</div>@if($quotations->isEmpty())<div class="empty">لا توجد عروض.</div>@else<div style="overflow:auto"><table><thead><tr><th>الرقم</th><th>العميل</th><th>الإصدار</th><th>القيمة</th><th>الصلاحية</th><th>الحالة</th><th></th></tr></thead><tbody>@foreach($quotations as $quote)<tr><td>{{ $quote->quote_no }}</td><td>{{ $quote->client->name }}</td><td>{{ $quote->version }}</td><td>{{ number_format($quote->priceInclVat(),2) }}</td><td>{{ $quote->valid_until->format('Y-m-d') }}</td><td><span class="pill {{ in_array($quote->status,['accepted','converted'])?'green':($quote->status==='sent'?'amber':'grey') }}">{{ ['draft'=>'مسودة','sent'=>'مرسل','accepted'=>'معتمد','converted'=>'عقد','rejected'=>'مرفوض'][$quote->status]??$quote->status }}</span></td><td style="white-space:nowrap">@if($quote->status==='draft')<form method="POST" action="{{ route('panel.quotation.send',$quote) }}" style="display:inline">@csrf<button class="btn small">إرسال للعميل</button></form>@endif @if(in_array($quote->status,['sent','accepted']))<form method="POST" action="{{ route('panel.quotation.convert',$quote) }}" style="display:inline">@csrf<button class="btn small ghost">تحويل لعقد</button></form>@endif @if($quote->convertedContract)<a href="{{ route('panel.client',$quote->client_id) }}">{{ $quote->convertedContract->contract_no }}</a>@endif</td></tr>@endforeach</tbody></table></div>@endif</div>

<div class="card"><div class="hd">الدفعات والاستحقاقات</div>@if($installments->isEmpty())<div class="empty">تُنشأ الدفعات تلقائيًا عند تحويل العرض إلى عقد.</div>@else<div style="overflow:auto"><table><thead><tr><th>العقد/العميل</th><th>الاستحقاق</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>تسجيل قبض</th></tr></thead><tbody>@foreach($installments as $i)<tr><td>{{ $i->contract->contract_no }}<br><small>{{ $i->contract->client->name }}</small></td><td>{{ $i->due_on->format('Y-m-d') }}</td><td>{{ number_format($i->total_amount,2) }}</td><td>{{ number_format($i->paid_amount,2) }}</td><td>{{ number_format($i->remaining(),2) }}</td><td><span class="pill {{ $i->status==='paid'?'green':($i->due_on->isPast()?'red':'amber') }}">{{ $i->status==='paid'?'مدفوعة':($i->due_on->isPast()?'متأخرة':($i->status==='partial'?'جزئية':'قادمة')) }}</span></td><td>@if($i->remaining()>0)<details><summary class="btn small ghost">سند قبض</summary><form method="POST" action="{{ route('panel.installment.payment',$i) }}" style="min-width:260px;padding-top:8px">@csrf<input name="amount" type="number" step="0.01" max="{{ $i->remaining() }}" placeholder="المبلغ" required><input name="paid_on" type="date" value="{{ now()->toDateString() }}" required><select name="method"><option value="bank_transfer">تحويل بنكي</option><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="online">إلكتروني</option></select><input name="reference" placeholder="المرجع"><button class="btn small">تسجيل</button></form></details>@endif</td></tr>@endforeach</tbody></table></div>@endif</div>

<div class="grid2"><div class="card"><div class="hd">عقود قاربت الانتهاء</div>@forelse($contractsEnding as $contract)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $contract->client->name }}</strong> — {{ $contract->contract_no }}<br><span class="pill amber">ينتهي {{ $contract->ends_on->format('Y-m-d') }}</span></div>@empty<div class="empty">لا عقود تنتهي خلال 60 يوماً.</div>@endforelse</div><div class="card"><div class="hd">آخر سندات القبض</div>@forelse($payments as $payment)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $payment->receipt_no }}</strong> — {{ $payment->client->name }}<br>{{ number_format($payment->amount,2) }} ر.س · {{ $payment->paid_on->format('Y-m-d') }}</div>@empty<div class="empty">لا مدفوعات.</div>@endforelse</div></div>
@endsection
