@extends('layouts.panel')
@section('title','إدارة الأسطول')
@section('content')
@php
    $documentLabels=['registration'=>'الاستمارة','insurance'=>'التأمين','inspection'=>'الفحص الدوري','operation_card'=>'بطاقة التشغيل','authorization'=>'التفويض','other'=>'أخرى'];
    $orderLabels=['preventive'=>'صيانة وقائية','repair'=>'إصلاح','accident'=>'حادث','tires'=>'إطارات','oil'=>'زيوت','other'=>'أخرى'];
    $statusLabels=['open'=>'مفتوح','approved'=>'معتمد','in_progress'=>'قيد الإصلاح','completed'=>'مكتمل','cancelled'=>'ملغى'];
@endphp
<h1>إدارة الأسطول</h1>
<div class="sub">وثائق وتجديدات، فحص سلامة، أوامر إصلاح وصيانة دورية، توقف وتكلفة فعلية لكل سيارة.</div>

<div class="kpis">
    <div class="kpi"><div class="v">{{ $vehicles->count() }}</div><div class="l">سيارة نشطة</div></div>
    <div class="kpi"><div class="v">{{ $vehicles->where('operational_status','out_of_service')->count() }}</div><div class="l">خارج الخدمة</div></div>
    <div class="kpi"><div class="v">{{ $expiringDocuments->count() }}</div><div class="l">وثائق تحتاج تجديدًا</div></div>
    <div class="kpi"><div class="v">{{ number_format($vehicles->sum('expenses_sum_amount'),2) }}</div><div class="l">إجمالي تكلفة الأسطول</div></div>
</div>

<div class="card"><div class="hd">إضافة سيارة</div><div class="bd"><details><summary style="cursor:pointer;color:var(--teal)">فتح نموذج السيارة</summary><form method="POST" action="{{ route('panel.fleet.vehicle') }}" style="margin-top:12px">@csrf
    <div class="grid3"><div class="field"><label>اللوحة</label><input name="plate" required></div><div class="field"><label>الرمز الداخلي</label><input name="internal_code"></div><div class="field"><label>الفرع</label><select name="operating_branch_id"><option value="">الإدارة العامة</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->company->name }} / {{ $branch->name }}</option>@endforeach</select></div></div>
    <div class="grid3"><div class="field"><label>الشركة المصنعة</label><input name="make"></div><div class="field"><label>الموديل</label><input name="model"></div><div class="field"><label>السنة</label><input type="number" name="year"></div></div>
    <div class="grid3"><div class="field"><label>رقم الهيكل VIN</label><input name="vin" dir="ltr"></div><div class="field"><label>العداد الحالي</label><input type="number" step="0.1" name="current_odometer_km" value="0"></div><div class="field"><label>الفني المستلم</label><input type="number" name="assigned_user_id" placeholder="رقم المستخدم"></div></div><button class="btn">إضافة السيارة</button>
</form></details></div></div>

<div class="card"><div class="hd">تنبيهات التجديد</div><div style="overflow:auto"><table><thead><tr><th>السيارة</th><th>الوثيقة</th><th>المزود</th><th>الانتهاء</th><th>الحالة</th><th></th></tr></thead><tbody>@forelse($expiringDocuments as $document)@php $days=now()->startOfDay()->diffInDays($document->expires_on,false); @endphp<tr><td><strong>{{ $document->vehicle->plate }}</strong></td><td>{{ $documentLabels[$document->type] ?? $document->type }}</td><td>{{ $document->provider ?? '—' }}</td><td>{{ $document->expires_on->format('Y-m-d') }}</td><td><span class="pill {{ $days<0?'red':($days<=30?'amber':'grey') }}">{{ $days<0?'منتهية منذ '.abs($days).' يوم':($days===0?'تنتهي اليوم':'بعد '.$days.' يوم') }}</span></td><td>@if($document->file_path)<a class="btn small ghost" href="{{ route('panel.fleet.document.download',$document) }}">تنزيل</a>@endif</td></tr>@empty<tr><td colspan="6" class="empty">لا توجد وثائق قريبة من الانتهاء.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="hd">أوامر الصيانة والإصلاح المفتوحة</div><div style="overflow:auto"><table><thead><tr><th>الأمر والسيارة</th><th>الوصف</th><th>التكلفة</th><th>الحالة</th><th>الإجراء التالي</th></tr></thead><tbody>@forelse($openOrders as $order)<tr><td><strong>{{ $order->order_no }}</strong><br>{{ $order->vehicle->plate }}</td><td>{{ $orderLabels[$order->type] ?? $order->type }} · {{ $order->description }}<br><small>{{ $order->vendor_name }}</small></td><td>{{ number_format($order->estimated_cost,2) }}</td><td><span class="pill {{ $order->status==='in_progress'?'amber':'grey' }}">{{ $statusLabels[$order->status] }}</span></td><td><form method="POST" action="{{ route('panel.fleet.maintenance.transition',$order) }}">@csrf
    @if($order->status==='open')<input type="hidden" name="status" value="approved"><button class="btn small">اعتماد</button>
    @elseif($order->status==='approved')<input type="hidden" name="status" value="in_progress"><div class="grid3"><input name="vendor_name" placeholder="الورشة"><input name="quote_reference" placeholder="مرجع العرض"><input type="number" step="0.01" name="estimated_cost" value="{{ $order->estimated_cost }}"></div><button class="btn small">بدء الإصلاح</button>
    @else<input type="hidden" name="status" value="completed"><div class="grid3"><input type="number" step="0.01" name="actual_cost" placeholder="التكلفة الفعلية" required><input type="number" step="0.1" name="odometer_km" placeholder="العداد"><input type="date" name="completed_on" value="{{ now()->toDateString() }}"></div><div class="grid2"><input type="date" name="next_service_on" title="موعد الصيانة القادمة"><input type="number" step="0.1" name="next_service_odometer_km" placeholder="عداد الصيانة القادمة"></div><button class="btn small">إكمال وإعادة السيارة</button>@endif
    </form></td></tr>@empty<tr><td colspan="5" class="empty">لا توجد أوامر مفتوحة.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="hd">آخر فحوص السلامة</div><div style="overflow:auto"><table><thead><tr><th>السيارة</th><th>الفاحص</th><th>التاريخ والعداد</th><th>النتيجة</th><th>الملاحظات</th></tr></thead><tbody>@forelse($recentInspections as $inspection)<tr><td>{{ $inspection->vehicle->plate }}</td><td>{{ $inspection->inspector?->name ?? '—' }}</td><td>{{ $inspection->inspected_at->format('Y-m-d H:i') }}<br>{{ number_format($inspection->odometer_km,1) }} كم</td><td><span class="pill {{ $inspection->is_roadworthy?'green':'red' }}">{{ $inspection->is_roadworthy?'صالحة':'خارج الخدمة' }}</span></td><td>{{ $inspection->defects ?? '—' }} @if($inspection->photo_path)<a href="{{ route('panel.fleet.inspection.photo',$inspection) }}">عرض الصورة</a>@endif</td></tr>@empty<tr><td colspan="5" class="empty">لا توجد فحوص بعد.</td></tr>@endforelse</tbody></table></div></div>

<h2 style="font-size:19px">ملفات السيارات</h2>
@foreach($vehicles as $vehicle)
<div class="card"><div class="hd"><strong>{{ $vehicle->plate }}</strong><span class="pill {{ $vehicle->operational_status==='available'?'green':'red' }}">{{ $vehicle->operational_status==='available'?'متاحة':'خارج الخدمة' }}</span><span style="margin-inline-start:auto;font-size:12px;color:var(--muted)">التكلفة: {{ number_format($vehicle->expenses_sum_amount ?? 0,2) }} ر.س · العداد: {{ number_format($vehicle->current_odometer_km,1) }} كم</span></div>
<div class="bd"><div class="grid2">
<details><summary style="cursor:pointer;color:var(--teal);font-weight:600">بيانات السيارة وخطة الصيانة</summary><form method="POST" action="{{ route('panel.fleet.vehicle.update',$vehicle) }}" style="margin-top:12px">@csrf @method('PUT')
    <div class="grid3"><div class="field"><label>اللوحة</label><input name="plate" value="{{ $vehicle->plate }}" required></div><div class="field"><label>الرمز</label><input name="internal_code" value="{{ $vehicle->internal_code }}"></div><div class="field"><label>الفرع</label><select name="operating_branch_id"><option value="">الإدارة العامة</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($vehicle->operating_branch_id===$branch->id)>{{ $branch->company->name }} / {{ $branch->name }}</option>@endforeach</select></div></div>
    <div class="grid3"><input name="make" value="{{ $vehicle->make }}" placeholder="الشركة"><input name="model" value="{{ $vehicle->model }}" placeholder="الموديل"><input type="number" name="year" value="{{ $vehicle->year }}" placeholder="السنة"></div>
    <div class="grid3"><input name="vin" value="{{ $vehicle->vin }}" placeholder="VIN" dir="ltr"><input type="number" step="0.1" name="current_odometer_km" value="{{ $vehicle->current_odometer_km }}"><input type="number" name="assigned_user_id" value="{{ $vehicle->assigned_user_id }}" placeholder="رقم الفني"></div>
    <div class="grid3"><input type="date" name="last_service_on" value="{{ $vehicle->last_service_on?->format('Y-m-d') }}"><input type="date" name="next_service_on" value="{{ $vehicle->next_service_on?->format('Y-m-d') }}"><input type="number" step="0.1" name="next_service_odometer_km" value="{{ $vehicle->next_service_odometer_km }}" placeholder="عداد الصيانة القادمة"></div><button class="btn small">حفظ</button>
</form></details>
<details><summary style="cursor:pointer;color:var(--teal);font-weight:600">وثيقة أو تجديد</summary><form method="POST" action="{{ route('panel.fleet.document',$vehicle) }}" enctype="multipart/form-data" style="margin-top:12px">@csrf
    <div class="grid3"><select name="type">@foreach($documentLabels as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select><input name="document_number" placeholder="رقم الوثيقة"><input name="provider" placeholder="المزود/شركة التأمين"></div>
    <div class="grid3"><input type="date" name="issued_on"><input type="date" name="expires_on"><input type="file" name="file" accept="application/pdf,image/png,image/jpeg,image/webp"></div>
    <div class="grid3"><input name="coverage_type" placeholder="نوع التغطية"><input type="number" step="0.01" name="insured_value" placeholder="قيمة التغطية"><input name="notes" placeholder="ملاحظات"></div><button class="btn small">حفظ الوثيقة</button>
</form></details>
<details><summary style="cursor:pointer;color:var(--teal);font-weight:600">فتح أمر صيانة أو إصلاح</summary><form method="POST" action="{{ route('panel.fleet.maintenance',$vehicle) }}" style="margin-top:12px">@csrf
    <div class="grid3"><select name="type">@foreach($orderLabels as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select><select name="priority"><option value="normal">عادي</option><option value="high">مرتفع</option><option value="urgent">عاجل</option><option value="low">منخفض</option></select><input type="date" name="opened_on" value="{{ now()->toDateString() }}" required></div>
    <div class="field"><label>وصف العطل أو العمل</label><textarea name="description" required></textarea></div><div class="grid3"><input name="vendor_name" placeholder="الورشة المقترحة"><input type="number" step="0.01" name="estimated_cost" placeholder="التكلفة المتوقعة"><input type="date" name="scheduled_for"></div><label><input type="checkbox" name="causes_outage" value="1" checked style="width:auto"> توقف السيارة أثناء الإصلاح</label><button class="btn small">فتح الأمر</button>
</form></details>
<details><summary style="cursor:pointer;color:var(--teal);font-weight:600">فحص السلامة اليومي</summary><form method="POST" action="{{ route('panel.fleet.inspection',$vehicle) }}" enctype="multipart/form-data" style="margin-top:12px">@csrf
    <div class="field"><label>العداد</label><input type="number" step="0.1" name="odometer_km" value="{{ $vehicle->current_odometer_km }}" required></div>
    <div class="grid3">@foreach(['tires'=>'الإطارات','brakes'=>'الفرامل','lights'=>'الأنوار','fluids'=>'الزيوت والسوائل','body'=>'الهيكل','cleanliness'=>'النظافة'] as $key=>$label)<label style="color:var(--ink)"><input type="checkbox" name="{{ $key }}" value="1" checked style="width:auto"> {{ $label }} سليمة</label>@endforeach</div>
    <div class="grid2"><textarea name="defects" placeholder="العيوب والملاحظات"></textarea><input type="file" name="photo" accept="image/png,image/jpeg,image/webp"></div><button class="btn small">حفظ الفحص</button>
</form></details>
<details><summary style="cursor:pointer;color:var(--teal);font-weight:600">تسجيل مصروف</summary><form method="POST" action="{{ route('panel.fleet.expense',$vehicle) }}" style="margin-top:12px">@csrf
    <div class="grid3"><select name="category"><option value="fuel">وقود</option><option value="maintenance">صيانة</option><option value="insurance">تأمين</option><option value="registration">استمارة</option><option value="inspection">فحص</option><option value="fine">مخالفة</option><option value="other">أخرى</option></select><input type="number" step="0.01" name="amount" placeholder="المبلغ" required><input type="date" name="incurred_on" value="{{ now()->toDateString() }}" required></div><div class="grid3"><input type="number" step="0.1" name="odometer_km" placeholder="العداد"><input name="reference" placeholder="المرجع"><input name="note" placeholder="ملاحظة"></div><button class="btn small">حفظ المصروف</button>
</form></details>
</div></div>
@if($vehicle->documents->isNotEmpty())<div style="overflow:auto"><table><thead><tr><th>الوثيقة</th><th>الرقم</th><th>الانتهاء</th><th></th></tr></thead><tbody>@foreach($vehicle->documents as $document)<tr><td>{{ $documentLabels[$document->type] ?? $document->type }}</td><td>{{ $document->document_number }}</td><td>{{ $document->expires_on?->format('Y-m-d') ?? '—' }}</td><td>@if($document->file_path)<a href="{{ route('panel.fleet.document.download',$document) }}">تنزيل</a>@endif</td></tr>@endforeach</tbody></table></div>@endif
</div>
@endforeach
@endsection
