@extends('layouts.panel')
@section('title','ذكاء الأعطال والأصول')
@section('content')
<h1>ذكاء الأعطال والأصول</h1><div class="sub">قواعد قابلة للتفسير الآن، والتنبؤ الإحصائي لا يُفعّل إلا بعد بلوغ حد البيانات الموثوق.</div>
<div class="grid3"><div class="stat"><b>{{ $readiness['completed'] }}</b><span>زيارة مكتملة / {{ $readiness['minimum_completed'] }}</span></div><div class="stat"><b>{{ $readiness['coded'] }}</b><span>زيارة بأكواد عطل وتشخيص / {{ $readiness['minimum_coded'] }}</span></div><div class="stat"><b>{{ $readiness['ready']?'جاهز':'غير جاهز' }}</b><span>حالة نموذج التنبؤ</span></div></div>
<div class="card"><div class="hd">نموذج تعلم آلي لعودة العطل خلال 90 يومًا</div><div class="bd">@if($trainedModel)<div class="grid3"><div class="stat"><b>{{ number_format($trainedModel->accuracy*100,1) }}%</b><span>الدقة على عينة تحقق منفصلة</span></div><div class="stat"><b>{{ number_format($trainedModel->precision*100,1) }}%</b><span>Precision</span></div><div class="stat"><b>{{ number_format($trainedModel->recall*100,1) }}%</b><span>Recall</span></div></div><small>تدرب على {{ $trainedModel->training_samples }} عينة واختُبر على {{ $trainedModel->validation_samples }} عينة في {{ $trainedModel->trained_at->format('Y-m-d H:i') }}.</small>@foreach($trainedModel->predictions->take(10) as $prediction)<div class="row"><div><strong>{{ $prediction->asset->site->client->name }} — {{ $prediction->asset->name }}</strong><span class="muted">أفق التنبؤ حتى {{ $prediction->horizon_ends_on->format('Y-m-d') }}</span></div><span class="pill {{ $prediction->risk_score>=.7?'red':($prediction->risk_score>=.4?'amber':'green') }}">{{ number_format($prediction->risk_score*100,1) }}%</span></div>@endforeach @else<p>لم يُدرّب نموذج بعد. يمنع النظام التدريب حتى تتوفر عينة زمنية كافية.</p>@endif<form method="POST" action="{{ route('panel.intelligence.train') }}">@csrf<button class="btn">تدريب وتحقق الآن</button></form></div></div>
<div class="card"><div class="hd">مؤشر صحة المعدات واقتراح الاستبدال</div><div style="overflow:auto"><table><thead><tr><th>الأصل</th><th>العمر</th><th>الأعطال</th><th>تكلفة 12 شهرًا</th><th>الصحة</th><th>القرار</th></tr></thead><tbody>@foreach($assetHealth as $row)<tr><td>{{ $row['asset']->site->client->name }} — {{ $row['asset']->name }}</td><td>{{ $row['ageYears'] }} سنة</td><td>{{ $row['faults90'] }} / 90 يوم · {{ $row['faults365'] }} / سنة</td><td>{{ number_format($row['cost'],2) }}</td><td><span class="pill {{ $row['health']<40?'red':($row['health']<70?'amber':'green') }}">{{ $row['health'] }}/100</span></td><td>{{ $row['replace']?'قارن الاستبدال بالإصلاح':'استمرار الصيانة والمراقبة' }}</td></tr>@endforeach</tbody></table></div></div>
@if($readiness['ready'])<div class="card"><div class="hd">التنبؤ الإحصائي بالأعطال بعد اكتمال البيانات</div>@forelse($predictions as $prediction)<div class="bd"><strong>{{ $prediction['asset']->site->client->name }} — {{ $prediction['asset']->name }}</strong><br>العطل {{ $prediction['fault_code'] }} متوقع قرب {{ $prediction['predicted_on']->format('Y-m-d') }} وفق متوسط {{ $prediction['average_days'] }} يومًا و{{ $prediction['samples'] }} حالات · ثقة {{ $prediction['confidence'] }}%</div>@empty<div class="empty">البيانات العامة كافية، لكن لا يوجد نمط متكرر ثلاث مرات لأصل واحد بعد.</div>@endforelse</div>@endif
<div class="grid2"><div class="card"><div class="hd">قطعة استُبدلت 3 مرات لدى عميل خلال 90 يومًا</div>@forelse($repeatParts as $row)<div class="bd"><strong>{{ $row->client_name }} — {{ $row->part_name }}</strong><br><span class="pill red">{{ $row->replacements }} زيارات صرف</span></div>@empty<div class="empty">لا توجد إشارة تكرار حرجة.</div>@endforelse</div><div class="card"><div class="hd">موردون ودفعات ذات فشل مرتفع</div>@forelse($supplierFailures as $row)<div class="bd"><strong>{{ $row->supplier_name }}</strong><br>{{ $row->failures }} بلاغ فشل / {{ $row->received_lots }} دفعة <span class="pill amber">{{ $row->failure_rate===null?'لا تكفي بيانات المقام':$row->failure_rate.'%' }}</span></div>@empty<div class="empty">لا توجد بلاغات فشل مرتبطة بمورد.</div>@endforelse</div></div>
<div class="grid2"><div class="card"><div class="hd">تسجيل فشل قطعة</div><div class="bd"><form method="POST" action="{{ route('panel.intelligence.failure') }}">@csrf<div class="field"><label>القطعة</label><select name="part_id">@foreach($parts as $part)<option value="{{ $part->id }}">{{ $part->name }}</option>@endforeach</select></div><div class="field"><label>الدفعة / التسلسلي</label><select name="inventory_lot_id"><option value="">غير معروف</option>@foreach($lots as $lot)<option value="{{ $lot->id }}">{{ $lot->part->name }} — {{ $lot->serial_number ?: $lot->lot_number }} — {{ $lot->supplier?->name }}</option>@endforeach</select></div><div class="grid2"><select name="asset_id"><option value="">أصل غير محدد</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->site->client->name }} — {{ $asset->name }}</option>@endforeach</select><select name="visit_id"><option value="">زيارة غير محددة</option>@foreach($visits as $visit)<option value="{{ $visit->id }}">#{{ $visit->id }} {{ $visit->site->name }}</option>@endforeach</select></div><input name="failure_kind" placeholder="نوع الفشل" required><textarea name="note" placeholder="الملاحظات"></textarea><button class="btn">تسجيل البلاغ</button></form></div></div>
<div class="card"><div class="hd">إضافة حل إلى قاعدة المعرفة</div><div class="bd"><form method="POST" action="{{ route('panel.intelligence.article') }}">@csrf<div class="grid2"><input name="fault_code" placeholder="كود العطل"><input name="asset_type" placeholder="نوع المعدة"></div><input name="title" placeholder="عنوان الحل" required><textarea name="symptoms" placeholder="الأعراض"></textarea><textarea name="diagnosis" placeholder="التشخيص" required></textarea><textarea name="solution" placeholder="خطوات الحل" required></textarea><select name="suggested_part_ids[]" multiple>@foreach($parts as $part)<option value="{{ $part->id }}">{{ $part->name }}</option>@endforeach</select><button class="btn">نشر الحل</button></form></div></div></div>
<div class="card"><div class="hd">قاعدة المعرفة</div>@forelse($articles as $article)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $article->fault_code ? '['.$article->fault_code.'] ' : '' }}{{ $article->title }}</strong><p>{{ $article->diagnosis }}</p><small>{{ $article->solution }}</small></div>@empty<div class="empty">أضف أول حل موثق.</div>@endforelse</div>
@endsection
