@extends('layouts.panel')
@section('title','الجدولة والإدارة التشغيلية')
@section('content')
<h1>الجدولة والإدارة التشغيلية</h1>
<div class="sub">عرض يومي وأسبوعي وشهري، مع سحب الزيارة إلى الفني واليوم المطلوب والتحقق من زمن الطريق والوردية والغياب والسيارة.</div>

<form method="GET" class="card"><div class="bd" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div class="field" style="margin:0"><label>العرض</label><select name="view"><option value="day" @selected($viewMode==='day')>يومي</option><option value="week" @selected($viewMode==='week')>أسبوعي</option><option value="month" @selected($viewMode==='month')>شهري</option></select></div><div class="field" style="margin:0"><label>التاريخ</label><input type="date" name="date" value="{{ $start->format('Y-m-d') }}"></div><button class="btn">عرض</button></div></form>

<div class="card"><div class="hd">تقويم الفنيين الأسبوعي — يدعم اليوم والأسبوع والشهر؛ اسحب البطاقة لتغيير الفني أو اليوم</div><div style="overflow:auto"><table><thead><tr><th>الفني</th>@for($d=0;$d<$dayCount;$d++)<th>{{ $start->copy()->addDays($d)->translatedFormat('D d/m') }}</th>@endfor</tr></thead><tbody>
@foreach($technicians as $tech)<tr><td><strong>{{ $tech->name }}</strong>@if($tech->is_emergency_backup)<br><span class="pill green">احتياط طوارئ</span>@endif<br><small>{{ substr($tech->shift_start,0,5) }}–{{ substr($tech->shift_end,0,5) }}</small></td>
@for($d=0;$d<$dayCount;$d++)@php $day=$start->copy()->addDays($d);$jobs=$visits->where('assigned_user_id',$tech->id)->filter(fn($v)=>$v->scheduled_start?->isSameDay($day)); @endphp
<td class="schedule-cell" data-technician="{{ $tech->id }}" data-date="{{ $day->format('Y-m-d') }}" style="min-width:150px">@forelse($jobs as $visit)<a draggable="true" data-visit="{{ $visit->id }}" data-time="{{ $visit->scheduled_start->format('H:i') }}" href="{{ route('panel.visit',$visit) }}" style="display:block;background:var(--teal-50);padding:7px;border-radius:7px;margin-bottom:5px"><b>{{ $visit->scheduled_start->format('H:i') }}</b> {{ $visit->site->client->name }}<br><small>{{ $visit->site->name }} @if($visit->estimated_arrival_at)· وصول {{ $visit->estimated_arrival_at->format('H:i') }}@endif</small></a>@empty<span style="color:var(--muted)">متاح</span>@endforelse</td>@endfor</tr>@endforeach
<tr><td><strong>غير مسند</strong></td>@for($d=0;$d<$dayCount;$d++)@php $day=$start->copy()->addDays($d);$jobs=$visits->whereNull('assigned_user_id')->filter(fn($v)=>$v->scheduled_start?->isSameDay($day)); @endphp<td>@foreach($jobs as $visit)<a draggable="true" data-visit="{{ $visit->id }}" data-time="{{ $visit->scheduled_start->format('H:i') }}" href="{{ route('panel.visit',$visit) }}" class="pill amber">{{ $visit->scheduled_start->format('H:i') }} {{ $visit->site->name }}</a>@endforeach</td>@endfor</tr>
</tbody></table></div></div>

<div class="grid2"><div class="card"><div class="hd">غياب الفني وإعادة التوزيع</div><div class="bd"><form method="POST" action="{{ route('panel.operations.absence') }}">@csrf<select name="user_id">@foreach($technicians as $tech)<option value="{{ $tech->id }}">{{ $tech->name }}</option>@endforeach</select><div class="grid2"><input type="date" name="starts_on" required><input type="date" name="ends_on" required></div><input name="reason" placeholder="سبب الغياب" required><button class="btn">اعتماد الغياب وإعادة التوزيع</button></form></div>@foreach($absences as $absence)<div class="bd" style="border-top:1px solid var(--line)"><strong>{{ $absence->user->name }}</strong> · {{ $absence->starts_on->format('Y-m-d') }} — {{ $absence->ends_on->format('Y-m-d') }}<br><small>{{ $absence->reason }}</small></div>@endforeach</div>
<div class="card"><div class="hd">تعطل سيارة وإعادة التوزيع</div><div class="bd"><form method="POST" action="{{ route('panel.operations.outage') }}">@csrf<select name="vehicle_id">@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->plate }} — {{ $vehicle->assignedUser?->name }}</option>@endforeach</select><div class="grid2"><input type="datetime-local" name="starts_at" required><input type="datetime-local" name="ends_at"></div><input name="reason" placeholder="سبب التعطل" required><button class="btn">تسجيل التعطل وإعادة التوزيع</button></form></div>@foreach($outages as $outage)<div class="bd" style="border-top:1px solid var(--line)"><strong>{{ $outage->vehicle->plate }}</strong> · {{ $outage->vehicle->assignedUser?->name }}<br><small>{{ $outage->reason }} — منذ {{ $outage->starts_at->format('Y-m-d H:i') }}</small></div>@endforeach</div></div>

<div class="card"><div class="hd">اقتراح توزيع الزيارات غير المسندة</div><div style="overflow:auto"><table><thead><tr><th>الزيارة</th><th>الموعد</th><th>أفضل الاقتراحات</th></tr></thead><tbody>@forelse($visits->whereNull('assigned_user_id') as $visit)<tr><td><a href="{{ route('panel.visit',$visit) }}"><strong>{{ $visit->site->client->name }} — {{ $visit->site->name }}</strong></a><br><small>{{ $visit->workOrder?->title }}</small></td><td>{{ $visit->scheduled_start?->format('Y-m-d H:i') }}</td><td>@forelse($suggestions->get($visit->id,collect()) as $suggestion)<form method="POST" action="{{ route('panel.visit.assign',$visit) }}" style="display:inline-block;margin:3px">@csrf<input type="hidden" name="user_id" value="{{ $suggestion['technician']->id }}"><button class="btn small ghost" title="{{ implode(' · ',$suggestion['reasons']) }}">{{ $suggestion['technician']->name }} · {{ $suggestion['score'] }}</button></form>@empty<span class="pill red">لا يوجد فني متاح بلا تعارض</span>@endforelse</td></tr>@empty<tr><td colspan="3" class="empty">كل الزيارات مسندة.</td></tr>@endforelse</tbody></table></div></div>

<div class="grid2"><div class="card"><div class="hd">أصول تتكرر أعطالها</div>@forelse($assetSignals as $asset)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $asset->site->client->name }} — {{ $asset->name }}</strong><br><span class="pill {{ $asset->signal==='critical'?'red':'amber' }}">{{ $asset->faults_90d }} خلال 90 يومًا · {{ $asset->faults_365d }} خلال سنة</span></div>@empty<div class="empty">لا توجد إشارة تكرار كافية.</div>@endforelse</div><div class="card"><div class="hd">قطع كثيرة الاستخدام</div>@forelse($partSignals as $part)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $part->name }}</strong><br><span class="pill amber">{{ $part->issues_90d }} صرف في {{ $part->visits_90d }} زيارة</span></div>@empty<div class="empty">لا توجد بيانات متكررة كافية.</div>@endforelse</div></div>

<div class="card"><div class="hd">طلبات المواعيد من العملاء</div><div style="overflow:auto"><table><thead><tr><th>العميل والموقع</th><th>الطلب</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>@forelse($serviceRequests as $item)<tr><td>{{ $item->client->name }}<br><small>{{ $item->site->name }}</small></td><td>{{ $item->description }}<br><small>{{ $item->preferred_date->format('Y-m-d') }}</small></td><td>{{ $item->status }}</td><td>@if($item->status==='pending')<form method="POST" action="{{ route('panel.service-request.convert',$item) }}">@csrf<input name="response_note" placeholder="ملاحظة"><button class="btn small">اعتماد</button></form><form method="POST" action="{{ route('panel.service-request.reject',$item) }}">@csrf<input name="response_note" placeholder="سبب الرفض" required><button class="btn small ghost">رفض</button></form>@else{{ $item->response_note }}@endif</td></tr>@empty<tr><td colspan="4" class="empty">لا توجد طلبات.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="hd">اعتراضات وتقييمات تحتاج متابعة</div>@forelse($feedbackItems as $feedback)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $feedback->visit->site->client->name }} — {{ $feedback->rating }}/5</strong><p>{{ $feedback->comment }}</p>@if($feedback->status!=='resolved')<form method="POST" action="{{ route('panel.feedback.review',$feedback) }}">@csrf<select name="status"><option value="reviewed">تحت المتابعة</option><option value="resolved">تم الحل</option></select><input name="supervisor_note" placeholder="إجراء المتابعة" required><button class="btn small">حفظ</button></form>@endif</div>@empty<div class="empty">لا توجد شكاوى مفتوحة.</div>@endforelse</div>

<div class="card"><div class="hd">اعتراضات رسمية على تقارير الزيارات</div>@forelse($disputes as $dispute)<div class="bd" style="border-bottom:1px solid var(--line)"><strong>{{ $dispute->visit->site->client->name }} — زيارة #{{ $dispute->visit_id }}</strong><br><span class="pill amber">{{ $dispute->category }} · {{ $dispute->public_reference }}</span><p>{{ $dispute->description }}</p><form method="POST" action="{{ route('panel.operations.dispute',$dispute) }}">@csrf<select name="status"><option value="reviewed">تحت المراجعة</option><option value="resolved">مقبول وتمت المعالجة</option><option value="rejected">مرفوض مع التوضيح</option></select><input name="resolution_note" placeholder="نتيجة المراجعة" required><button class="btn small">حفظ القرار</button></form></div>@empty<div class="empty">لا توجد اعتراضات رسمية مفتوحة.</div>@endforelse</div>

<script nonce="{{ $cspNonce }}">
let dragged=null;document.querySelectorAll('[draggable=true]').forEach(card=>card.addEventListener('dragstart',e=>{dragged={id:card.dataset.visit,time:card.dataset.time};e.dataTransfer.effectAllowed='move'}));document.querySelectorAll('.schedule-cell').forEach(cell=>{cell.addEventListener('dragover',e=>e.preventDefault());cell.addEventListener('drop',async e=>{e.preventDefault();if(!dragged)return;const time=prompt('وقت بدء الزيارة',dragged.time||'09:00');if(!time)return;const response=await fetch(`{{ url('operations/visits') }}/${dragged.id}/reschedule`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({assigned_user_id:Number(cell.dataset.technician),scheduled_start:`${cell.dataset.date}T${time}:00`})});if(response.ok)location.reload();else{const data=await response.json();alert(data.message||Object.values(data.errors||{}).flat().join('\n')||'تعذر تغيير الجدول')}})});
</script>
@endsection
