@extends('layouts.panel')
@section('title','الجدولة والإدارة التشغيلية')
@section('content')
<style nonce="{{ $cspNonce }}">
.ops-head{margin-bottom:16px}.ops-head .sub{max-width:760px;margin:0}.ops-tabs{display:flex;gap:6px;overflow-x:auto;padding:5px;background:#e9f1f3;border-radius:12px;margin-bottom:18px;scrollbar-width:thin}.ops-tabs a{color:#475569;white-space:nowrap;padding:9px 14px;border-radius:8px;font-weight:600;min-height:44px;display:inline-flex;align-items:center}.ops-tabs a:hover{background:#ffffffb3}.ops-tabs a.active{background:#fff;color:var(--teal);box-shadow:0 1px 3px #0f172a1f}.ops-filter{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.ops-filter .field{margin:0;min-width:150px}.table-scroll{overflow:auto;-webkit-overflow-scrolling:touch}.table-scroll table{min-width:680px}.schedule-table{min-width:max-content!important}.schedule-table th:first-child,.schedule-table td:first-child{position:sticky;right:0;z-index:1;background:#fff;min-width:150px}.schedule-table th:first-child{background:var(--teal-50);z-index:2}.schedule-card{display:block;background:var(--teal-50);padding:8px;border-radius:8px;margin-bottom:6px;border:1px solid #ccfbf1}.schedule-card:hover{border-color:#5eead4}.schedule-cell{min-width:165px;vertical-align:top;transition:background .15s}.schedule-cell.drag-over{background:#ccfbf1}.section-intro{color:var(--muted);font-size:13px;font-weight:400;margin-inline-start:auto}.stack-item{padding:16px;border-bottom:1px solid var(--line)}.stack-item:last-child{border-bottom:0}.stack-title{display:flex;justify-content:space-between;align-items:start;gap:12px;flex-wrap:wrap}.inline-actions{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.inline-actions input,.inline-actions select{min-width:170px;flex:1}.status-label{white-space:nowrap}@media(max-width:760px){.ops-tabs{margin-inline:-4px}.ops-tabs a{padding:9px 12px}.ops-filter>*{width:100%}.ops-filter .field{min-width:0}.card>.hd{align-items:start;flex-direction:column}.section-intro{margin:0}.stack-item{padding:14px}.inline-actions>*{width:100%}}
</style>

<div class="ops-head"><h1>الجدولة والإدارة التشغيلية</h1><div class="sub">تابع الجدول والطلبات والجودة والموارد من مساحة واحدة، دون ازدحام المعلومات غير المرتبطة بمهمتك الحالية.</div></div>
<nav class="ops-tabs" aria-label="أقسام الإدارة التشغيلية">
@foreach(['schedule'=>'الجدولة والتوزيع','requests'=>'طلبات العملاء','quality'=>'الجودة والاعتراضات','resources'=>'الغياب والمركبات'] as $tabKey=>$tabLabel)
<a href="{{ route('panel.operations',['tab'=>$tabKey]) }}" class="{{ $activeTab===$tabKey?'active':'' }}" @if($activeTab===$tabKey) aria-current="page" @endif>{{ $tabLabel }}</a>
@endforeach
</nav>

@if($activeTab==='schedule')
<form method="GET" class="card"><input type="hidden" name="tab" value="schedule"><div class="bd ops-filter"><div class="field"><label for="schedule-view">نطاق العرض</label><select id="schedule-view" name="view"><option value="day" @selected($viewMode==='day')>يومي</option><option value="week" @selected($viewMode==='week')>أسبوعي</option><option value="month" @selected($viewMode==='month')>شهري</option></select></div><div class="field"><label for="schedule-date">البدء من تاريخ</label><input id="schedule-date" type="date" name="date" value="{{ $start->format('Y-m-d') }}"></div><button class="btn">تحديث التقويم</button></div></form>
<div class="card"><div class="hd">تقويم الفنيين الأسبوعي <span class="section-intro">اسحب الزيارة إلى الفني واليوم المطلوب؛ ويمكن التمرير أفقيًا.</span></div><div class="table-scroll" tabindex="0" aria-label="تقويم زيارات الفنيين"><table class="schedule-table"><thead><tr><th>الفني</th>@for($d=0;$d<$dayCount;$d++)<th>{{ $start->copy()->addDays($d)->translatedFormat('D d/m') }}</th>@endfor</tr></thead><tbody>
@forelse($technicians as $tech)<tr><td><strong>{{ $tech->name }}</strong>@if($tech->is_emergency_backup)<br><span class="pill green">احتياط طوارئ</span>@endif<br><small>{{ substr($tech->shift_start,0,5) }}–{{ substr($tech->shift_end,0,5) }}</small></td>@for($d=0;$d<$dayCount;$d++)@php $day=$start->copy()->addDays($d);$jobs=$visits->where('assigned_user_id',$tech->id)->filter(fn($v)=>$v->scheduled_start?->isSameDay($day)); @endphp<td class="schedule-cell" data-technician="{{ $tech->id }}" data-date="{{ $day->format('Y-m-d') }}">@forelse($jobs as $visit)<a draggable="true" data-visit="{{ $visit->id }}" data-time="{{ $visit->scheduled_start->format('H:i') }}" href="{{ route('panel.visit',$visit) }}" class="schedule-card"><b>{{ $visit->scheduled_start->format('H:i') }}</b> {{ $visit->site->client->name }}<br><small>{{ $visit->site->name }} @if($visit->estimated_arrival_at)· وصول {{ $visit->estimated_arrival_at->format('H:i') }}@endif</small></a>@empty<span style="color:var(--muted)">متاح</span>@endforelse</td>@endfor</tr>@empty<tr><td colspan="{{ $dayCount+1 }}" class="empty">لا يوجد فنيون نشطون لعرض جدولهم.</td></tr>@endforelse
<tr><td><strong>غير مسند</strong></td>@for($d=0;$d<$dayCount;$d++)@php $day=$start->copy()->addDays($d);$jobs=$visits->whereNull('assigned_user_id')->filter(fn($v)=>$v->scheduled_start?->isSameDay($day)); @endphp<td>@forelse($jobs as $visit)<a draggable="true" data-visit="{{ $visit->id }}" data-time="{{ $visit->scheduled_start->format('H:i') }}" href="{{ route('panel.visit',$visit) }}" class="schedule-card"><b>{{ $visit->scheduled_start->format('H:i') }}</b> {{ $visit->site->name }}</a>@empty<span style="color:var(--muted)">—</span>@endforelse</td>@endfor</tr></tbody></table></div></div>
<div class="card"><div class="hd">اقتراح توزيع الزيارات غير المسندة <span class="section-intro">تعتمد الاقتراحات على التوفر والتعارضات.</span></div><div class="table-scroll"><table><thead><tr><th>الزيارة</th><th>الموعد</th><th>أفضل الاقتراحات</th></tr></thead><tbody>@forelse($visits->whereNull('assigned_user_id') as $visit)<tr><td><a href="{{ route('panel.visit',$visit) }}"><strong>{{ $visit->site->client->name }} — {{ $visit->site->name }}</strong></a><br><small>{{ $visit->workOrder?->title }}</small></td><td>{{ $visit->scheduled_start?->format('Y-m-d H:i') }}</td><td>@forelse($suggestions->get($visit->id,collect()) as $suggestion)<form method="POST" action="{{ route('panel.visit.assign',$visit) }}" style="display:inline-block;margin:3px">@csrf<input type="hidden" name="user_id" value="{{ $suggestion['technician']->id }}"><button class="btn small ghost" title="{{ implode(' · ',$suggestion['reasons']) }}">{{ $suggestion['technician']->name }} · {{ $suggestion['score'] }}</button></form>@empty<span class="pill red">لا يوجد فني متاح بلا تعارض</span>@endforelse</td></tr>@empty<tr><td colspan="3" class="empty">كل الزيارات مسندة، ولا توجد إجراءات مطلوبة.</td></tr>@endforelse</tbody></table></div></div>
<script nonce="{{ $cspNonce }}">let dragged=null;document.querySelectorAll('[draggable=true]').forEach(card=>card.addEventListener('dragstart',e=>{dragged={id:card.dataset.visit,time:card.dataset.time};e.dataTransfer.effectAllowed='move'}));document.querySelectorAll('.schedule-cell').forEach(cell=>{cell.addEventListener('dragover',e=>{e.preventDefault();cell.classList.add('drag-over')});cell.addEventListener('dragleave',()=>cell.classList.remove('drag-over'));cell.addEventListener('drop',async e=>{e.preventDefault();cell.classList.remove('drag-over');if(!dragged)return;const time=prompt('وقت بدء الزيارة',dragged.time||'09:00');if(!time)return;const response=await fetch(`{{ url('operations/visits') }}/${dragged.id}/reschedule`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({assigned_user_id:Number(cell.dataset.technician),scheduled_start:`${cell.dataset.date}T${time}:00`})});if(response.ok)location.reload();else{const data=await response.json();alert(data.message||Object.values(data.errors||{}).flat().join('\n')||'تعذر تغيير الجدول')}})});</script>

@elseif($activeTab==='requests')
<div class="card"><div class="hd">طلبات المواعيد من العملاء <span class="section-intro">تظهر الطلبات المنتظرة أولًا.</span></div><div class="table-scroll"><table><thead><tr><th>العميل والموقع</th><th>تفاصيل الطلب</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>@forelse($serviceRequests as $item)<tr><td><strong>{{ $item->client->name }}</strong><br><small>{{ $item->site->name }}</small></td><td>{{ $item->description }}<br><small>{{ $item->preferred_date->format('Y-m-d') }}</small></td><td><span class="pill {{ $item->status==='pending'?'amber':($item->status==='converted'?'green':'grey') }} status-label">{{ ['pending'=>'بانتظار المراجعة','converted'=>'تم الاعتماد','rejected'=>'مرفوض'][$item->status]??$item->status }}</span></td><td>@if($item->status==='pending')<form method="POST" action="{{ route('panel.service-request.convert',$item) }}" class="inline-actions">@csrf<input name="response_note" aria-label="ملاحظة اعتماد الطلب" placeholder="ملاحظة اختيارية"><button class="btn small">اعتماد</button></form><form method="POST" action="{{ route('panel.service-request.reject',$item) }}" class="inline-actions" style="margin-top:8px">@csrf<input name="response_note" aria-label="سبب رفض الطلب" placeholder="سبب الرفض" required><button class="btn small ghost">رفض</button></form>@else{{ $item->response_note?:'لا توجد ملاحظة' }}@endif</td></tr>@empty<tr><td colspan="4" class="empty">لا توجد طلبات مواعيد حاليًا.</td></tr>@endforelse</tbody></table></div></div>

@elseif($activeTab==='quality')
<div class="grid2"><div class="card"><div class="hd">أصول تتكرر أعطالها</div>@forelse($assetSignals as $asset)<div class="stack-item"><strong>{{ $asset->site->client->name }} — {{ $asset->name }}</strong><br><span class="pill {{ $asset->signal==='critical'?'red':'amber' }}">{{ $asset->faults_90d }} خلال 90 يومًا · {{ $asset->faults_365d }} خلال سنة</span></div>@empty<div class="empty">لا توجد إشارات تكرار أعطال تتطلب المتابعة.</div>@endforelse</div><div class="card"><div class="hd">قطع كثيرة الاستخدام</div>@forelse($partSignals as $part)<div class="stack-item"><strong>{{ $part->name }}</strong><br><span class="pill amber">{{ $part->issues_90d }} صرف في {{ $part->visits_90d }} زيارة</span></div>@empty<div class="empty">لا توجد أنماط استخدام متكرر كافية.</div>@endforelse</div></div>
<div class="card"><div class="hd">تقييمات وشكاوى تحتاج متابعة</div>@forelse($feedbackItems as $feedback)<div class="stack-item"><div class="stack-title"><strong>{{ $feedback->visit->site->client->name }} — التقييم {{ $feedback->rating }}/5</strong><span class="pill amber">{{ ['new'=>'جديد','reviewed'=>'تحت المتابعة','resolved'=>'تم الحل'][$feedback->status]??$feedback->status }}</span></div><p>{{ $feedback->comment?:'لم يضف العميل تعليقًا.' }}</p>@if($feedback->status!=='resolved')<form method="POST" action="{{ route('panel.feedback.review',$feedback) }}" class="inline-actions">@csrf<select name="status" aria-label="حالة متابعة الشكوى"><option value="reviewed">تحت المتابعة</option><option value="resolved">تم الحل</option></select><input name="supervisor_note" placeholder="إجراء المتابعة" required><button class="btn small">حفظ المتابعة</button></form>@endif</div>@empty<div class="empty">لا توجد شكاوى مفتوحة تحتاج المتابعة.</div>@endforelse</div>
<div class="card"><div class="hd">اعتراضات رسمية على تقارير الزيارات</div>@forelse($disputes as $dispute)<div class="stack-item"><div class="stack-title"><strong>{{ $dispute->visit->site->client->name }} — زيارة #{{ $dispute->visit_id }}</strong><span class="pill amber">{{ $dispute->category }} · {{ $dispute->public_reference }}</span></div><p>{{ $dispute->description }}</p><form method="POST" action="{{ route('panel.operations.dispute',$dispute) }}" class="inline-actions">@csrf<select name="status" aria-label="قرار الاعتراض"><option value="reviewed">تحت المراجعة</option><option value="resolved">مقبول وتمت المعالجة</option><option value="rejected">مرفوض مع التوضيح</option></select><input name="resolution_note" placeholder="نتيجة المراجعة" required><button class="btn small">حفظ القرار</button></form></div>@empty<div class="empty">لا توجد اعتراضات رسمية مفتوحة.</div>@endforelse</div>

@elseif($activeTab==='resources')
<div class="grid2"><div class="card"><div class="hd">غياب الفني وإعادة التوزيع</div><div class="bd"><form method="POST" action="{{ route('panel.operations.absence') }}">@csrf<div class="field"><label for="absence-user">الفني</label><select id="absence-user" name="user_id" required><option value="">اختر الفني</option>@foreach($technicians as $tech)<option value="{{ $tech->id }}">{{ $tech->name }}</option>@endforeach</select></div><div class="grid2"><div class="field"><label for="absence-from">من</label><input id="absence-from" type="date" name="starts_on" required></div><div class="field"><label for="absence-to">إلى</label><input id="absence-to" type="date" name="ends_on" required></div></div><div class="field"><label for="absence-reason">سبب الغياب</label><input id="absence-reason" name="reason" required></div><button class="btn">اعتماد وإعادة التوزيع</button></form></div>@forelse($absences as $absence)<div class="stack-item"><strong>{{ $absence->user->name }}</strong> · {{ $absence->starts_on->format('Y-m-d') }} — {{ $absence->ends_on->format('Y-m-d') }}<br><small>{{ $absence->reason }}</small></div>@empty<div class="empty">لا توجد حالات غياب حالية أو قادمة.</div>@endforelse</div>
<div class="card"><div class="hd">تعطل سيارة وإعادة التوزيع</div><div class="bd"><form method="POST" action="{{ route('panel.operations.outage') }}">@csrf<div class="field"><label for="outage-vehicle">السيارة</label><select id="outage-vehicle" name="vehicle_id" required><option value="">اختر السيارة</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->plate }} — {{ $vehicle->assignedUser?->name??'غير مسندة' }}</option>@endforeach</select></div><div class="grid2"><div class="field"><label for="outage-from">وقت بدء التعطل</label><input id="outage-from" type="datetime-local" name="starts_at" required></div><div class="field"><label for="outage-to">العودة المتوقعة</label><input id="outage-to" type="datetime-local" name="ends_at"></div></div><div class="field"><label for="outage-reason">سبب التعطل</label><input id="outage-reason" name="reason" required></div><button class="btn">تسجيل وإعادة التوزيع</button></form></div>@forelse($outages as $outage)<div class="stack-item"><strong>{{ $outage->vehicle->plate }}</strong> · {{ $outage->vehicle->assignedUser?->name??'غير مسندة' }}<br><small>{{ $outage->reason }} — منذ {{ $outage->starts_at->format('Y-m-d H:i') }}</small></div>@empty<div class="empty">لا توجد سيارات متعطلة حاليًا.</div>@endforelse</div></div>
@endif
@endsection
