<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#0b3b35">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="تطبيق المسوق لإدارة العملاء المحتملين والعروض والمتابعات والأداء.">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="manifest" href="{{ route('sales.manifest') }}">
    <link rel="icon" href="/client-icon.svg" type="image/svg+xml">
    <title>@yield('title', 'محور المبيعات')</title>
    <style nonce="{{ $cspNonce }}">
        :root{--night:#092f2b;--deep:#0b3b35;--teal:#0d766a;--mint:#dff7ef;--lime:#b9eb83;--cream:#f7f8f2;--paper:#fff;--ink:#17211f;--muted:#687572;--line:#dfe7e3;--red:#b94141;--amber:#a76605;--green:#16745d;--shadow:0 16px 45px rgba(9,47,43,.09)}
        *{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:88px;overflow-x:hidden}body{margin:0;background:var(--cream);color:var(--ink);font-family:Tahoma,"Segoe UI",system-ui,sans-serif;line-height:1.65;overflow-wrap:anywhere}body.modal-open{overflow:hidden}a{color:inherit;text-decoration:none}button,input,select,textarea{font:inherit}button{cursor:pointer}:focus-visible{outline:3px solid #6ee7b7;outline-offset:3px;border-radius:7px}.skip-link{position:fixed;z-index:200;inset-block-start:8px;inset-inline-start:8px;transform:translateY(-150%);padding:9px 14px;border-radius:9px;background:#fff;color:var(--night);font-weight:900;box-shadow:var(--shadow)}.skip-link:focus{transform:none}
        .top{position:sticky;top:0;z-index:50;background:rgba(9,47,43,.96);color:#fff;box-shadow:0 8px 30px rgba(9,47,43,.16);backdrop-filter:blur(12px)}.bar{width:min(1240px,calc(100% - 32px));min-height:72px;margin:auto;display:flex;align-items:center;gap:24px}.brand{display:flex;align-items:center;gap:11px;font-weight:900}.brand-mark{width:39px;height:39px;border-radius:13px;background:var(--lime);color:var(--night);display:grid;place-items:center;font-size:20px}.brand small{display:block;color:#a9cec8;font-size:9px;font-weight:400}.desktop-nav{display:flex;gap:20px;margin-inline-start:auto}.desktop-nav a{color:#cfe5e1;font-size:13px}.desktop-nav a:hover{color:#fff}.user-menu{display:flex;align-items:center;gap:10px}.avatar{width:34px;height:34px;border-radius:50%;background:#1b5e55;display:grid;place-items:center;font-weight:800}.user-meta{font-size:11px}.user-meta small{display:block;color:#9ec6c0}.logout{border:1px solid rgba(255,255,255,.2);background:transparent;color:#fff;border-radius:10px;padding:6px 10px}
        main{width:min(1240px,calc(100% - 32px));margin:auto;padding:26px 0 104px}.flash{padding:12px 15px;border-radius:13px;margin-bottom:14px}.flash.ok{background:#dff8ee;color:#145b49}.flash.err{background:#fee7e7;color:#7d2020}.offline-bar{display:none;position:fixed;top:72px;inset-inline:0;z-index:45;background:#7c2d12;color:#fff;text-align:center;padding:7px;font-size:12px}.offline .offline-bar{display:block}
        .btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;gap:7px;border:0;border-radius:12px;background:var(--teal);color:#fff;padding:10px 16px;font-weight:800}.btn:hover{filter:brightness(.96)}.btn.light{background:#fff;color:var(--night)}.btn.ghost{background:transparent;border:1px solid var(--line);color:var(--deep)}.btn.small{padding:7px 11px;font-size:12px}.btn.danger{background:#fff1f1;color:var(--red);border:1px solid #f4caca}.icon{font-size:18px;line-height:1}.section-title{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:30px 0 13px}.section-title h2{margin:0;font-size:21px}.section-title p{margin:2px 0 0;color:var(--muted);font-size:12px}.link{color:var(--teal);font-size:12px;font-weight:800}
        .card{background:var(--paper);border:1px solid var(--line);border-radius:19px;box-shadow:0 1px 0 rgba(9,47,43,.02)}.field{margin-bottom:13px}label{display:block;color:var(--muted);font-size:11px;margin-bottom:4px}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:12px;background:#fff;padding:11px 12px;color:var(--ink)}input:focus,select:focus,textarea:focus{outline:3px solid rgba(13,118,106,.12);border-color:var(--teal)}textarea{resize:vertical}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.muted{color:var(--muted);font-size:11px}.pill{display:inline-flex;align-items:center;padding:3px 9px;border-radius:999px;background:#eef3f1;color:#53635f;font-size:10px;font-weight:800}.pill.new{background:#e8f1ff;color:#285b98}.pill.qualified{background:#e8f8f1;color:#16745d}.pill.proposal{background:#f1ebff;color:#6847a7}.pill.negotiation{background:#fff2d7;color:#96620b}.pill.won{background:#dff8d9;color:#32712c}.pill.lost{background:#f3e8e8;color:#975050}
        .bottom-nav{display:none}.install{display:none;position:fixed;inset:auto 16px 82px;z-index:80;border:0;border-radius:14px;padding:12px 16px;background:var(--lime);color:var(--night);box-shadow:0 16px 50px rgba(0,0,0,.2);font-weight:900}.install.show{display:block}.account-card{text-align:center;padding:12px 0}.account-avatar{width:72px;height:72px;margin:auto;border-radius:24px;background:var(--mint);color:var(--deep);display:grid;place-items:center;font-size:30px;font-weight:900}.account-card h3{margin:11px 0 1px}.account-actions{display:grid;gap:8px;margin-top:18px}.account-actions .btn{width:100%}
        .modal{position:fixed;inset:0;z-index:100;display:none;align-items:flex-end;justify-content:center;background:rgba(4,26,24,.58);padding:20px}.modal.open{display:flex}.sheet{width:min(680px,100%);max-height:min(92vh,92dvh);overflow:auto;overscroll-behavior:contain;background:var(--cream);border-radius:24px;padding:22px;box-shadow:0 30px 90px rgba(0,0,0,.25)}.sheet-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:16px}.sheet-head h2{margin:0}.close-modal{width:44px;height:44px;flex:0 0 44px;border:0;border-radius:50%;background:#e5ece9;color:var(--night)}
        @media(max-width:780px){.bar{min-height:64px}.desktop-nav,.user-meta,.logout{display:none}.user-menu{margin-inline-start:auto}main{width:min(100% - 22px,700px);padding-top:16px}.grid3,.grid2{grid-template-columns:1fr}.bottom-nav{display:grid;position:fixed;z-index:60;bottom:0;inset-inline:0;grid-template-columns:repeat(5,1fr);padding:7px max(8px,env(safe-area-inset-right)) calc(7px + env(safe-area-inset-bottom)) max(8px,env(safe-area-inset-left));background:rgba(255,255,255,.98);border-top:1px solid var(--line);box-shadow:0 -8px 28px rgba(9,47,43,.08)}.bottom-nav a,.bottom-nav button{min-height:52px;border:0;background:none;color:#687572;text-align:center;font-size:10px;padding:3px}.bottom-nav b{display:block;color:var(--deep);font-size:19px;line-height:1.2}.modal{padding:0;align-items:flex-end}.sheet{border-radius:24px 24px 0 0;max-height:94vh;padding:20px 15px calc(20px + env(safe-area-inset-bottom))}.offline-bar{top:64px}}
        @media(prefers-reduced-motion:no-preference){.modal.open .sheet{animation:rise .24s ease-out}.card{transition:transform .18s ease,box-shadow .18s ease}.card:hover{transform:translateY(-2px);box-shadow:var(--shadow)}@keyframes rise{from{transform:translateY(35px);opacity:.6}}}
    </style>
    @stack('styles')
</head>
<body>
<a class="skip-link" href="#main-content">تجاوز إلى المحتوى</a>
@include('partials.language-switcher')
<div class="offline-bar">أنت غير متصل الآن — البيانات الحساسة غير محفوظة على الجهاز، وستعود بعد الاتصال.</div>
<header class="top"><div class="bar">
    <a class="brand" href="{{ route('sales.home') }}"><span class="brand-mark">م</span><span>{{ $panelCompany?->name ?? 'محور' }}<small>تطبيق فريق المبيعات</small></span></a>
    <nav class="desktop-nav"><a href="#today">اليوم</a><a href="#pipeline">مسار المبيعات</a><a href="#quotations">العروض</a><a href="#performance">أدائي</a></nav>
    <div class="user-menu"><span class="avatar">{{ mb_substr(auth('web')->user()->name,0,1) }}</span><span class="user-meta">{{ auth('web')->user()->name }}<small>{{ auth('web')->user()->operatingBranch?->name ?? 'الإدارة العامة' }}</small></span><form method="POST" action="{{ route('panel.logout') }}">@csrf<button class="logout">خروج</button></form></div>
</div></header>
<main id="main-content" tabindex="-1">
    @if(session('ok'))<div class="flash ok" role="status">{{ session('ok') }}</div>@endif
    @if(session('err'))<div class="flash err" role="alert">{{ session('err') }}</div>@endif
    @if($errors->any())<div class="flash err" role="alert">@foreach($errors->all() as $error)<div>• {{ $error }}</div>@endforeach</div>@endif
    @yield('content')
</main>
<nav class="bottom-nav"><a href="#today"><b>⌂</b>اليوم</a><a href="#pipeline"><b>▦</b>المسار</a><a href="#quotations"><b>▤</b>العروض</a><button type="button" data-open-modal="lead-modal"><b>＋</b>فرصة</button><button type="button" data-open-modal="account-modal"><b>●</b>حسابي</button></nav>
<div class="modal" id="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-title"><div class="sheet"><div class="sheet-head"><h2 id="account-title">حسابي</h2><button class="close-modal" type="button" data-close-modal aria-label="إغلاق">×</button></div><div class="account-card"><div class="account-avatar">{{ mb_substr(auth('web')->user()->name,0,1) }}</div><h3>{{ auth('web')->user()->name }}</h3><span class="muted">{{ auth('web')->user()->operatingBranch?->name ?? 'الإدارة العامة' }}</span><div class="account-actions">@if(isset($pushConfigured) && $pushConfigured)<button class="btn ghost" id="enablePush" type="button" data-public-key="{{ $pushPublicKey }}">{{ $pushSubscribed ? 'تحديث تنبيهات الجهاز' : 'تفعيل تنبيهات الجهاز' }}</button>@endif @if(Route::has('panel.performance') && auth('web')->user()->canPanel('performance'))<a class="btn ghost" href="{{ route('panel.performance',['category'=>'marketers']) }}">تقرير الأداء الكامل</a>@endif<form method="POST" action="{{ route('panel.logout') }}">@csrf<button class="btn danger">تسجيل خروج آمن</button></form></div></div></div></div>
<button id="installApp" class="install" type="button">تثبيت تطبيق المسوق</button>
<script nonce="{{ $cspNonce }}">
let installPrompt;const installButton=document.getElementById('installApp');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.classList.add('show')});
installButton.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.classList.remove('show')});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('{{ route('sales.service-worker') }}',{scope:'/sales/'}))}
const syncNetwork=()=>document.documentElement.classList.toggle('offline',!navigator.onLine);window.addEventListener('online',syncNetwork);window.addEventListener('offline',syncNetwork);syncNetwork();
const modalFocusable='a[href],button:not([disabled]),input:not([disabled]):not([type="hidden"]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';let modalTrigger=null;
const closeModal=modal=>{if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');modalTrigger?.focus();modalTrigger=null};
const openModal=(modal,trigger)=>{if(!modal)return;modalTrigger=trigger;modal.classList.add('open');modal.removeAttribute('aria-hidden');document.body.classList.add('modal-open');requestAnimationFrame(()=>modal.querySelector(modalFocusable)?.focus())};
document.querySelectorAll('.modal').forEach(modal=>modal.setAttribute('aria-hidden','true'));
document.querySelectorAll('[data-open-modal]').forEach(button=>button.addEventListener('click',()=>openModal(document.getElementById(button.dataset.openModal),button)));
document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>closeModal(button.closest('.modal'))));
document.querySelectorAll('.modal').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeModal(modal)}));
document.addEventListener('keydown',event=>{const modal=document.querySelector('.modal.open');if(!modal)return;if(event.key==='Escape'){event.preventDefault();closeModal(modal);return}if(event.key!=='Tab')return;const items=[...modal.querySelectorAll(modalFocusable)].filter(item=>item.offsetParent!==null);if(!items.length){event.preventDefault();return}const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
const pushButton=document.getElementById('enablePush');
const base64Bytes=value=>{const pad='='.repeat((4-value.length%4)%4),raw=atob((value+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))};
if(pushButton&&'PushManager' in window){pushButton.addEventListener('click',async()=>{try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('لم تُمنح صلاحية التنبيهات');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();subscription??=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64Bytes(pushButton.dataset.publicKey)});const response=await fetch('{{ route('sales.push.subscribe') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'},body:JSON.stringify({...subscription.toJSON(),contentEncoding:PushManager.supportedContentEncodings?.[0]||'aes128gcm'})});if(!response.ok)throw new Error('تعذر حفظ الاشتراك');pushButton.textContent='تم تفعيل تنبيهات الجهاز ✓'}catch(error){pushButton.textContent=error.message}})}
let lastSalesNotification={{ isset($salesNotifications) ? (int)($salesNotifications->max('id') ?? 0) : 0 }};
const pollSalesNotifications=async()=>{if(document.hidden||!navigator.onLine)return;try{const response=await fetch('{{ route('sales.notifications') }}?after='+lastSalesNotification,{headers:{Accept:'application/json'}});if(!response.ok)return;const payload=await response.json();for(const item of payload.data){lastSalesNotification=Math.max(lastSalesNotification,item.id);if(Notification.permission==='granted'){const registration=await navigator.serviceWorker.ready;registration.showNotification(item.subject||'تنبيه مبيعات',{body:item.body,icon:'/client-icon.svg',data:{url:'{{ route('sales.home', absolute:false) }}'}})}}}catch(_){}};
setInterval(pollSalesNotifications,60000);
</script>
@include('partials.form-accessibility')
@stack('scripts')
@include('partials.runtime-localization')
</body></html>
