@extends('layouts.client')
@section('title', $client->name.' — دارك')
@section('content')
<section class="hero"><h1>مرحباً، {{ auth('client')->user()->name }}</h1><p>{{ $client->name }} · كل مواقعك وأصولك وتقارير الصيانة</p>@if($client->sites->first()?->emergency_qr_secret)<a class="emergency" href="{{ route('emergency.create',$client->sites->first()->emergency_qr_secret) }}">رفع بلاغ طارئ</a>@endif</section>
<div style="margin-top:14px"><a class="btn" href="{{ route('client.service-request') }}">طلب موعد صيانة</a></div>
<div class="grid" style="margin-top:14px"><div class="card"><b>{{ $client->sites->count() }}</b><span class="muted">المواقع</span></div><div class="card"><b>{{ $client->sites->sum(fn($site)=>$site->assets->count()) }}</b><span class="muted">الأصول</span></div><div class="card"><b>{{ $client->contracts->where('status','active')->count() }}</b><span class="muted">العقود النشطة</span></div></div>
<h2>العروض والدفعات</h2><div class="list">@forelse($quotations as $quotation)<div class="row"><div><strong>{{ $quotation->title }}</strong><span class="muted">{{ $quotation->quote_no }} · {{ number_format($quotation->priceInclVat(),2) }} ر.س للدورة</span></div><a class="btn ghost" href="{{ route('client.quotation',$quotation) }}">{{ $quotation->status === 'sent' ? 'مراجعة واعتماد' : 'التفاصيل' }}</a></div>@empty<div class="card muted">لا توجد عروض أسعار مرسلة.</div>@endforelse @foreach($client->contracts->flatMap->installments->sortBy('due_on')->take(12) as $installment)<div class="row"><div><strong>دفعة العقد {{ $installment->contract->contract_no ?? '' }} #{{ $installment->installment_no }}</strong><span class="muted">استحقاق {{ $installment->due_on->format('Y-m-d') }} · المتبقي {{ number_format($installment->remaining(),2) }} ر.س</span></div><span class="pill {{ $installment->status === 'paid' ? 'green' : 'amber' }}">{{ ['pending'=>'مستحقة','partial'=>'مدفوعة جزئياً','paid'=>'مدفوعة'][$installment->status] ?? $installment->status }}</span></div>@endforeach</div>
<h2>العقود والإيصالات</h2><div class="list">@foreach($client->contracts as $contract)<div class="row"><div><strong>{{ $contract->contract_no }}</strong><span class="muted">{{ $contract->starts_on->format('Y-m-d') }} — {{ $contract->ends_on?->format('Y-m-d') }}</span></div><a class="btn ghost" href="{{ route('client.contract',$contract) }}">{{ $contract->signed_at?'عرض العقد':'مراجعة وتوقيع' }}</a></div>@endforeach @foreach($client->payments->sortByDesc('paid_on')->take(20) as $payment)<div class="row"><div><strong>{{ $payment->receipt_no }}</strong><span class="muted">{{ number_format($payment->amount,2) }} ر.س · {{ $payment->paid_on->format('Y-m-d') }}</span></div><a class="btn ghost" target="_blank" href="{{ route('client.payment.receipt',$payment) }}">تنزيل الإيصال</a></div>@endforeach</div>
<h2>موافقات الأعمال الإضافية</h2><div class="list">@forelse($additionalApprovals as $approval)<div class="row"><div><strong>{{ $approval->title }}</strong><span class="muted">{{ $approval->visit->site->name }} · {{ number_format($approval->total_amount,2) }} ر.س</span></div><a class="btn {{ $approval->status==='pending'?'':'ghost' }}" href="{{ route('client.additional-work',$approval) }}">{{ $approval->status==='pending'?'اتخاذ القرار':'عرض القرار' }}</a></div>@empty<div class="card muted">لا توجد أعمال إضافية بانتظار قرارك.</div>@endforelse</div>
<h2>طلبات المواعيد</h2><div class="list">@forelse($serviceRequests as $serviceRequest)<div class="row"><div><strong>{{ $serviceRequest->site->name }} — {{ $serviceRequest->asset?->name ?? 'خدمة عامة للموقع' }}</strong><span class="muted">{{ $serviceRequest->preferred_date->format('Y-m-d') }} · {{ ['morning'=>'صباحًا','afternoon'=>'ظهرًا','evening'=>'مساءً'][$serviceRequest->preferred_time_slot] ?? $serviceRequest->preferred_time_slot }} @if($serviceRequest->response_note) · {{ $serviceRequest->response_note }}@endif</span></div><span class="pill {{ $serviceRequest->status==='converted'?'green':($serviceRequest->status==='rejected'?'red':'amber') }}">{{ ['pending'=>'بانتظار المراجعة','converted'=>'تم تأكيد الزيارة','rejected'=>'مرفوض'][$serviceRequest->status] ?? $serviceRequest->status }}</span></div>@empty<div class="card muted">لا توجد طلبات مواعيد.</div>@endforelse</div>
<h2>المواقع والأصول</h2><div class="list">@foreach($client->sites as $site)<div class="row"><div><strong>{{ $site->name }}</strong><span class="muted">{{ $site->address ?: 'العنوان غير مسجل' }} · {{ $site->assets->count() }} أصل</span></div>@if($site->emergency_qr_secret)<a class="btn" href="{{ route('emergency.create',$site->emergency_qr_secret) }}">بلاغ لهذا الموقع</a>@endif</div>@endforeach</div>
<h2>سجل المعدات</h2><div class="list">@foreach($client->sites as $site)@foreach($site->assets as $asset)<div class="row"><div><strong>{{ $asset->name }}</strong><span class="muted">{{ $site->name }} · {{ $asset->serial_number ?: 'بلا رقم تسلسلي' }}</span></div><a class="btn ghost" target="_blank" href="{{ route('client.asset.history',$asset) }}">سجل الصيانة PDF</a></div>@endforeach @endforeach</div>
<h2>آخر الزيارات</h2><div class="list">@forelse($visits as $visit)<div class="row"><div><strong>{{ $visit->workOrder?->title }}</strong><span class="muted">{{ $visit->site?->name }} · {{ $visit->scheduled_start?->format('Y-m-d H:i') ?? 'لم يحدد الموعد' }} @if($visit->state==='en_route') · الوصول التقريبي {{ $visit->estimated_arrival_at?->format('H:i') ?? 'قيد الحساب' }}@endif</span></div><div><span class="pill {{ $visit->isClosed() ? 'green' : 'amber' }}">{{ ['scheduled'=>'مجدولة','en_route'=>'في الطريق','started'=>'قيد التنفيذ','paused'=>'متوقفة','awaiting_close'=>'بانتظار الإقفال','completed'=>'مكتملة','reopened'=>'أعيد فتحها'][$visit->state] ?? $visit->state }}</span> <a class="btn ghost" href="{{ route('client.visit',$visit) }}">التفاصيل</a></div></div>@empty<div class="card muted">لا توجد زيارات بعد.</div>@endforelse</div>
@endsection
