@extends('layouts.client')
@section('title','تفاصيل الزيارة — دارك')
@section('content')
<a href="{{ route('client.home') }}">← العودة</a><h1 style="margin-bottom:4px">{{ $visit->workOrder?->title }}</h1><div class="muted">{{ $visit->workOrder?->wo_number }} · {{ $visit->site?->name }}</div>
<div class="grid" style="margin-top:18px"><div class="card"><span class="muted">الحالة</span><b style="font-size:18px">{{ ['scheduled'=>'مجدولة','en_route'=>'في الطريق','started'=>'قيد التنفيذ','paused'=>'متوقفة','awaiting_close'=>'بانتظار الإقفال','completed'=>'مكتملة','reopened'=>'أعيد فتحها'][$visit->state] ?? $visit->state }}</b></div><div class="card"><span class="muted">الفني</span><b style="font-size:18px">{{ $visit->technician?->name ?? 'لم يُسند بعد' }}</b></div><div class="card"><span class="muted">الوصول التقريبي</span><b style="font-size:18px">{{ $visit->estimated_arrival_at?->format('Y-m-d H:i') ?? $visit->scheduled_start?->format('Y-m-d H:i') ?? 'غير محدد' }}</b><span class="muted">تقديري وقد يتغير حسب الطريق</span></div></div>
<div class="card" style="margin-top:14px"><strong>وصف الطلب</strong><p>{{ $visit->workOrder?->description ?: 'لا يوجد وصف إضافي.' }}</p></div>
@if($visit->state==='en_route' && $visit->technician_lat && $visit->technician_lng)@php($mapLat=round((float)$visit->technician_lat,3))@php($mapLng=round((float)$visit->technician_lng,3))<div class="card" style="margin-top:14px"><strong>موقع الفني التقريبي</strong><p class="muted">آخر تحديث {{ $visit->location_updated_at?->diffForHumans() }}. قُرّب الموقع إلى نحو 100 متر لحماية خصوصية الفني.</p><iframe title="خريطة موقع الفني" loading="lazy" style="width:100%;height:300px;border:0;border-radius:12px" src="https://www.openstreetmap.org/export/embed.html?bbox={{ $mapLng-0.012 }}%2C{{ $mapLat-0.008 }}%2C{{ $mapLng+0.012 }}%2C{{ $mapLat+0.008 }}&amp;layer=mapnik&amp;marker={{ $mapLat }}%2C{{ $mapLng }}"></iframe></div>@endif
@if($visit->isClosed())<a class="btn" href="{{ route('client.visit.report',$visit) }}" target="_blank">فتح تقرير الزيارة PDF</a>@endif
@if($visit->isClosed())
<div class="card" style="margin-top:16px"><strong>تقييم الزيارة</strong>@if($visit->feedback)<p>تم استلام تقييمك: <b>{{ $visit->feedback->rating }}/5</b>.</p>@else<form method="POST" action="{{ route('client.visit.feedback',$visit) }}">@csrf<div class="field"><label>التقييم</label><select name="rating" required><option value="5">5 — ممتاز</option><option value="4">4 — جيد جدًا</option><option value="3">3 — مقبول</option><option value="2">2 — غير مرضٍ</option><option value="1">1 — سيئ</option></select></div><div class="field"><label>هل تم حل المشكلة؟</label><select name="resolution_confirmed" required><option value="1">نعم</option><option value="0">لا</option></select></div><textarea name="comment" maxlength="1500" placeholder="ملاحظتك"></textarea><button class="btn">إرسال التقييم</button></form>@endif</div>
<div class="card" style="margin-top:16px"><strong>اعتراض على تقرير الزيارة</strong><p class="muted">يمكن الاعتراض على العمل أو القطع أو الوقت، ويُحفظ برقم متابعة مستقل.</p><form method="POST" action="{{ route('client.visit.dispute',$visit) }}">@csrf<select name="category"><option value="work">الأعمال المنفذة</option><option value="parts">القطع</option><option value="time">الوقت</option><option value="report">بيانات التقرير</option><option value="other">أخرى</option></select><textarea name="description" required maxlength="4000" placeholder="اشرح سبب الاعتراض"></textarea><button class="btn">فتح اعتراض</button></form>@foreach($disputes as $dispute)<div class="row"><div><strong>{{ $dispute->public_reference }}</strong><span class="muted">{{ $dispute->description }}</span></div><span class="pill {{ $dispute->status==='resolved'?'green':'amber' }}">{{ $dispute->status }}</span></div>@endforeach</div>
@endif
@endsection
